config/routes.rb
Rails.application.routes.draw do
  resources :mircoposts
  resources :users
  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mircopost.rb
class Mircopost < ApplicationRecord
  belongs_to :user
  validates :content, length: { maximum: 140 },
    presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :mircoposts
  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  def hello
    render html: "hello, world!"
  end
end

app/controllers/mircoposts_controller.rb
class MircopostsController < ApplicationController
  before_action :set_mircopost, only: [:show, :edit, :update, :destroy]

  # GET /mircoposts
  # GET /mircoposts.json
  def index
    @mircoposts = Mircopost.all
  end

  # GET /mircoposts/1
  # GET /mircoposts/1.json
  def show
  end

  # GET /mircoposts/new
  def new
    @mircopost = Mircopost.new
  end

  # GET /mircoposts/1/edit
  def edit
  end

  # POST /mircoposts
  # POST /mircoposts.json
  def create
    @mircopost = Mircopost.new(mircopost_params)

    respond_to do |format|
      if @mircopost.save
        format.html { redirect_to @mircopost, notice: 'Mircopost was successfully created.' }
        format.json { render :show, status: :created, location: @mircopost }
      else
        format.html { render :new }
        format.json { render json: @mircopost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mircoposts/1
  # PATCH/PUT /mircoposts/1.json
  def update
    respond_to do |format|
      if @mircopost.update(mircopost_params)
        format.html { redirect_to @mircopost, notice: 'Mircopost was successfully updated.' }
        format.json { render :show, status: :ok, location: @mircopost }
      else
        format.html { render :edit }
        format.json { render json: @mircopost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mircoposts/1
  # DELETE /mircoposts/1.json
  def destroy
    @mircopost.destroy
    respond_to do |format|
      format.html { redirect_to mircoposts_url, notice: 'Mircopost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mircopost
      @mircopost = Mircopost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mircopost_params
      params.require(:mircopost).permit(:content, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mircoposts_helper.rb
module MircopostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToyApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mircoposts/_form.html.erb
<%= form_with(model: mircopost, local: true) do |form| %>
  <% if mircopost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mircopost.errors.count, "error") %> prohibited this mircopost from being saved:</h2>

      <ul>
      <% mircopost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :mircopost_content %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :mircopost_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/mircoposts/edit.html.erb
<h1>Editing Mircopost</h1>

<%= render 'form', mircopost: @mircopost %>

<%= link_to 'Show', @mircopost %> |
<%= link_to 'Back', mircoposts_path %>

app/views/mircoposts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mircoposts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mircoposts.each do |mircopost| %>
      <tr>
        <td><%= mircopost.content %></td>
        <td><%= mircopost.user_id %></td>
        <td><%= link_to 'Show', mircopost %></td>
        <td><%= link_to 'Edit', edit_mircopost_path(mircopost) %></td>
        <td><%= link_to 'Destroy', mircopost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mircopost', new_mircopost_path %>

app/views/mircoposts/new.html.erb
<h1>New Mircopost</h1>

<%= render 'form', mircopost: @mircopost %>

<%= link_to 'Back', mircoposts_path %>

app/views/mircoposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @mircopost.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @mircopost.user_id %>
</p>

<%= link_to 'Edit', edit_mircopost_path(@mircopost) %> |
<%= link_to 'Back', mircoposts_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Microposts</strong><br>
  <% @user.mircoposts.each do |post| %>
    <%= post.content %><br>
  <% end %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>